### ISSUE TITLE
Починить, взрывающие верстку, баги текстовых полей интерфейса

### ISSUE THREAD

**Issue by basilred** [shri-team5/pepo#124]
- [x] «Константин Константинопольский» в качестве имени пользователя
- [x] Горизонтальный скрол на беспробельном поле текста в описании профиля
  <img width="325" alt="screen shot 2016-09-04 at 10 11 28" src="https://cloud.githubusercontent.com/assets/413033/18229625/03192fe4-7289-11e6-9873-3c91eaa813b3.png">

**Comment by Grimfrid** [comment]
Надо еще добавить

``` css
.tweet-item__text {
    word-break: break-all;
}
```
